### ISSUE TITLE
A ROM for one of the SNES MIAs has been discovered.

### ISSUE THREAD

**Issue by MeguCocoa** [SnowflakePowered/opengood#2]
That is the title of the following and the information about it.

Secret of the Stars (U) [T+Bra].smc

SIZE: 1573376
CRC32: 123578B2
MD5: F5A97F60B6E04442A43DEA73A343D174
SHA1: C3CF810CE00B75A29C75D83EA0C2267BDFFDBA27

**Comment by chyyran** [comment]
Dump found, verified, updated in 4cf524df596855d3c35dc517f08fb7febb305103

Thanks for letting me know. Apologies for the late update.
