### ISSUE TITLE
OpenNES - incorrect hashes

### ISSUE THREAD

**Issue by alexb3d** [SnowflakePowered/opengood#7]
Hello. 

I have two different romset downloaded from 'archive.org' and I'm using the OpenNES dat. 

I am using the JRomManager and it tells me that almost all of them have the wrong 'crc' sum. I test the roms through the terminal and indeed, they are not the same. 

The 'crc' of the dat are different from the two sets. But the two sets are identical.

For example...

dat: <rom name="!Clik! by Sly Dog Studios (2008) (PD).nes" size="16384" crc="**3e595bd2**"

Set 1: GoodNES (Missing 2 of 22096) ROM [!]
!Clik! by Sly Dog Studios (2008) (PD).nes
**f6a204a0**

Set 2: GoodNES [v3.23b] (22,095 of 22,096 ROMs)
!Clik! by Sly Dog Studios (2008) (PD).nes
**f6a204a0**

The same happens with md5 and sha1.
I have not tested the dats from other sets.

I am using the commands crc32, md5sum and sha1sum from the terminal, is this correct?

**Comment by chyyran** [comment]
OpenNES only verifies against the GoodTools NES set which is **not** necessarily completely clean dumps. The goal of the database is not to verify against new sets, but to preserve the GoodTools database in an open manner.

**Comment by Europia79** [comment]
@alexb3d heya, i'm actually working on a different NES project at the moment & i came across this (browsing out of curiosity):  So, I'm not a subject matter expert on this particular repository, but it appears that `OpenNES.dat` is unheadered, while you probably have headered ROMs:  Of which, there's iNes v1.0, iNes v2.0 as well as Signed Headers and also some ROMs have Footers:  All of these different scenarios create differe ROM files which result in different hashes.

Not sure what the solution would be for your situation as I don't deal in this area and plus, there are probably a variety of different solutions:  The easiest probably being just grabbing a different DAT file that accounts for the Headers ?

In the world of romhacking, we have a similar problem whereby we have to match the patch to the Parent/Baserom:  And for NES, this is further complicated by all the different Headers:  So, occasionally, i'll have to employ...

```bash
for file in *; do md5sum "$file"; md5sum <(xxd -ps -s 16 "$file" | xxd -ps -r); done
```

...to temporarily remove the Header & get BOTH the hash for the Headered & Unheadered ROMs.

**Comment by chyyran** [comment]
There is a script in the meta folder that strips the headers for unheadered entries in the NES dat

**Comment by alexb3d** [comment]
> Not sure what the solution would be for your situation as I don't deal in this area and plus, there are probably a variety of different solutions:...

It doesn't matter, I just want it to make RetroArch playlist, anyway, I can make the dats from the sets you get.
